--Create SUPPLIERS table 
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(255) NOT NULL,
    SUPP_CONTACT_NAME VARCHAR2(255),
    SUPP_ADDRESS VARCHAR2(255),
    SUPP_CONTACT_NUMBER VARCHAR2(50),
    SUPP_EMAIL VARCHAR2(255)
);

-- Create PURCHASE_ORDERS table
CREATE TABLE PURCHASE_ORDERS (
    ORDER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_REF VARCHAR2(50) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    SUPPLIER_ID NUMBER NOT NULL,
    ORDER_TOTAL_AMOUNT NUMBER,
    ORDER_DESCRIPTION VARCHAR2(255),
    ORDER_STATUS VARCHAR2(50),
    CONSTRAINT FK_ORDERS_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);

-- Create PURCHASE_ORDER_DETAILS table
CREATE TABLE PURCHASE_ORDER_LINES (
    ORDER_LINE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    ORDER_LINE_REF VARCHAR2(50) NOT NULL,
    ORDER_LINE_AMOUNT NUMBER,
    ORDER_LINE_DESCRIPTION VARCHAR2(255),
    ORDER_LINE_STATUS VARCHAR2(50),
    CONSTRAINT FK_ORDER_LINES_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PURCHASE_ORDERS(ORDER_ID)
);

-- Create INVOICES table
CREATE TABLE INVOICES (
    INVOICE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INVOICE_REFERENCE VARCHAR2(50) NOT NULL,
    INVOICE_DATE DATE NOT NULL,
    ORDER_ID NUMBER NOT NULL,
    INVOICE_STATUS VARCHAR2(50),
    INVOICE_HOLD_REASON VARCHAR2(255),
    INVOICE_AMOUNT NUMBER,
    INVOICE_DESCRIPTION VARCHAR2(255),
    CONSTRAINT FK_INVOICES_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PURCHASE_ORDERS(ORDER_ID)
);

